### ISSUE TITLE
ng serve 报错

### ISSUE THREAD

**Issue by grubed** [stbui/angular-material-app#10]
Windows7 x64
node v8.8.1
yarn v1.3.2
npm v5.4.1
用npm install安装可以运行
用yarn安装报错如下：

ERROR in D:/code/iris_web/node_modules/angularfire2/firebase.app.module.d.ts (5,22): Class 'FirebaseApp' incorrectly implements interface 'App'.
  Property 'firestore' is missing in type 'FirebaseApp'.
ERROR in D:/code/iris_web/node_modules/angularfire2/firebase.app.module.d.ts (12,28): Namespace 'firebase' has no exported member 'Promise'.

**Comment by stbui** [comment]
yarn 安装firebase版本造成的

https://github.com/angular/angularfire2/issues/1336
