### ISSUE TITLE
太牛了。能不能有不翻墙也能看的demo？

### ISSUE THREAD

**Issue by jackyped** [stbui/angular-material-app#16]

**Comment by stbui** [comment]
部分数据存在firebase上，是可以实时交互的。


~~这个是早期demo，数据是本地的
https://github.com/stbui/angular-material-chat-web-app~~

**Comment by alpeshvasani** [comment]
I want to call NotificationService from sigin components..but sucked at nullinjector provider for NotificationService....how did material/popover had injected this service?
