### ISSUE TITLE
Scroll bar problem 

### ISSUE THREAD

**Issue by duard** [stbui/angular-material-app#20]
Hello, I'm from Brazil, thanks for this nice project using Angular Material 2

My problem is : when I run the project on resolution below to 1920-1080 then I get some blank space at bottom of the screen and it create another scroll bar.
![scroolbar problem](https://user-images.githubusercontent.com/36894/37043503-839af146-213f-11e8-9a0b-c7b739cdd74f.PNG)

**Comment by duard** [comment]
![scroolbar problem 2](https://user-images.githubusercontent.com/36894/37044057-380ba2d2-2141-11e8-8889-e33377e40895.PNG)

**Comment by stbui** [comment]
Is it deleted?
```
mat-sidenav-container {
  height: 100%;
}
```
https://github.com/stbui/angular-material-app/blob/master/src/styles.scss#L37

**Comment by duard** [comment]
if I remove 

mat-sidenav-container {
  height: 100%;
}

1600x900 monitor

![scroll](https://user-images.githubusercontent.com/36894/37223593-c8270440-23af-11e8-90ab-e6309febf4cf.PNG)

**Comment by duard** [comment]
when I remove that 

```
mat-sidenav-container {
  height: 100%;
}
```

I cant scrool the content inside the page :-/

![inssue](https://user-images.githubusercontent.com/36894/37460300-97d2f30c-2829-11e8-94d2-2d749df037c8.PNG)
