### ISSUE TITLE
这个项目会一直维护么？

### ISSUE THREAD

**Issue by zuohuadong** [stbui/angular-material-app#21]
盈利方式呢？  会推出高级版之类的么

**Comment by stbui** [comment]
正在准备升级`angular 6 ` `material2` `FlexLayout`。
不会有高级版本，有时间的话可以会针对行业领域进行开发

**Comment by zuohuadong** [comment]
@stbui   我们也是公司，有一起合作的可能么？
项目地址： https://github.com/notadd
