### ISSUE TITLE
支持 json 生成表单

### ISSUE THREAD

**Issue by zuohuadong** [stbui/angular-material-app#22]
https://github.com/kousikpaul4u/react-jsonschema-form-mui
类似这样。

这样后端开发的童鞋可以不学Angular  就能做一些简单的表单。

**Comment by stbui** [comment]
感谢分享。
后端用angular做项目，还是要学点angular的

**Comment by zuohuadong** [comment]
嗯，只是为了方便做一些简单的表单。
http://github.com/notadd/notadd 
我们的项目。打算切换到 angular ...
一些简单的表单，后端自己实现，自己调试还是挺好的。

**Comment by stbui** [comment]
json-schema 基于angular封装的还是比较少，目前项目使用**angular2-json-schema-form**库编写示例页面。

**Comment by zuohuadong** [comment]
方便加微信或者QQ 细聊么？
