### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by cnbillow** [stbui/angular-material-app#25]
ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"D:/angular/angular-material-app/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by stbui** [comment]
能否提供更多的错误日记吗？

目前项目在mac上开发的，window开发没有测试过

**Comment by cnbillow** [comment]
\angular-material-app-master\node_modules\@angular\flex-layout\media-query\breakpoints\break-points.d.ts
master分支，npm install后如果下载到这个文件，打开就会提示#1的错误。编译也是。
https://stackoverflow.com/questions/49242601/angular-flex-has-no-exported-member-opaquetoken
