### ISSUE TITLE
项目分支说明

### ISSUE THREAD

**Issue by stbui** [stbui/angular-material-app#26]
master: 分支主要用于功能展示，不建议在此基础上开发。
base:  分支保留了基本的框架，可以在此基础上进行开发。
feature/xxx: 功能开发分支

**Comment by cnbillow** [comment]
如果有个增删改查结合table的例子就好了。这应该是最基本的了。

**Comment by stbui** [comment]
嗯，后续基于@swimlane/ngx-datatable做个完整的例子
