### ISSUE TITLE
Submenus itens - 带子菜单的菜单在侧边栏上

### ISSUE THREAD

**Issue by duard** [stbui/angular-material-app#31]
能够递归地创建菜单项。

```
- 菜单1
-   第1项
-    子项目1
```
各种级别和项目的菜单。

如果我无法清楚解释自己，我很抱歉。

**Comment by stbui** [comment]
示例代码
https://github.com/stbui/angular-material-app/blob/90eae2804a4b6fc1550f4f2a93592b13ed53fd09/src/app/admin/navigation/navigation.component.ts#L36-L45

**Comment by duard** [comment]
I will try this, thanks !
