### ISSUE TITLE
npm install卡死不动了

### ISSUE THREAD

**Issue by peng2013** [stbui/angular-material-app#41]
请问楼主的环境版本，谢谢

**Comment by stbui** [comment]
node:
v10.6.0
npm
6.3.0

**Comment by stbui** [comment]
你可以试试`npm install --verboase`将日志打印出来观察，可以依赖的包下载很慢
也可以修改下npm镜像：`npm config set registry http://registry.npm.taobao.org/`

**Comment by peng2013** [comment]
谢楼主 我把node版本升级成v10.9.0安装成功了
