### ISSUE TITLE
运行npm run build卡住不执行

### ISSUE THREAD

**Issue by alei78910** [stbui/angular-material-app#43]
1.运行npm start正常启动
2.支行ng build正常
3.运行npm run build卡在10% building modules 4/4 modules 0 active(node:484) DeprecationWarning: Tapable.plugin is deprecated. Use ne 92% chunk asset optimization UglifyJSPlugin就不往下执行了
4.npm 6.4.1、node v10.8.0、webpack 4.17.2、Angular CLI: 6.1.5、Angular: 6.1.6

**Comment by stbui** [comment]
不太清楚怎么回事，可以试试
```
node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --prod
```
