### ISSUE TITLE
Failed to load resource: the server responded with a status of 499 (Request has been forbidden by antivirus)

### ISSUE THREAD

**Issue by AliAUZ** [stbui/angular-material-app#47]
when I run the template I get this error in my browser

Failed to load resource: the server responded with a status of 499
 (Request has been forbidden by antivirus)

![er3](https://user-images.githubusercontent.com/29033729/50411628-a2517300-0855-11e9-8827-e878162bc456.png)

**Comment by elogicsoft** [comment]
Hi, I am also facing the same while uploading a simple image from laravel (5.7) blade form. I am using only laravel built in move function. Pls can you tell me how did you solved it..? Btw - i have found this link: https://forums.autodesk.com/t5/vault-forum/499-request-has-been-forbidden-by-antivirus/m-p/7639365#M71063   - can anybody helps me here. TIA.
