### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by laurent-grousset** [stbui/angular-material-app#51]
ERROR in src/app/admin/header/header.component.ts(28,20): error TS2339: Property 'enabled' does not exist on type 'false | (Screenfull & { default: false | (Screenfull & ...); })'.
  Property 'enabled' does not exist on type 'false'.
src/app/admin/header/header.component.ts(29,18): error TS2339: Property 'toggle' does not exist on type 'false | (Screenfull & { default: false | (Screenfull & ...); })'.
  Property 'toggle' does not exist on type 'false'.

**Comment by Hermoins** [comment]
yeah，I had the same problem。

**Comment by laurent-grousset** [comment]
3 years old issue. Closingit.
