### ISSUE TITLE
循环依赖

### ISSUE THREAD

**Issue by GitLuckyDog** [stbui/angular-material-app#6]
WARNING in Circular dependency detected:
src\app\component\notification\notification.component.ts -> src\app\component\notification\notification.service.ts -> src\app\component\not
ent.ts -> src\app\component\notification\notificat
ion.service.ts -> src\app\component\notification\notification.component.ts

WARNING in Circular dependency detected:
src\app\component\notification\notification.service.ts -> src\app\component\notification\notification.component.ts -> src\app\component\not
ification\notification.service.ts

**Comment by renocompass** [comment]
need to find a solution
