### ISSUE TITLE
npm run start Error

### ISSUE THREAD

**Issue by lymallor** [stbui/angular-material-app#7]
F:\www\angular-material-app (master)
λ npm run start

> angular-material-app@0.4.5 start F:\www\angular-material-app
> npm run build:themes && ng serve --extract-css

> angular-material-app@0.4.5 build:themes F:\www\angular-material-app
> npm run build:theme:deeppurple && npm run build:theme:indigo && npm run build:theme:pink && npm run build:theme:purple

> angular-material-app@0.4.5 build:theme:deeppurple F:\www\angular-material-app
> $(npm bin)/node-sass src/assets/custom-themes/deeppurple-amber.scss src/assets/deeppurple-amber.css

'$' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-app@0.4.5 build:theme:deeppurple: `$(npm bin)/node-sass src/assets/custom-themes/deeppurple-amber.scss src/assets/deeppurple-amber.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-material-app@0.4.5 build:theme:deeppurple script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-10-11T08_21_52_388Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-app@0.4.5 build:themes: `npm run build:theme:deeppurple && npm run build:theme:indigo && npm run build:theme:pink && npm run build:theme:purple`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-material-app@0.4.5 build:themes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-10-11T08_21_52_458Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-app@0.4.5 start: `npm run build:themes && ng serve --extract-css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-material-app@0.4.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-10-11T08_21_52_510Z-debug.log

F:\www\angular-material-app (master)

**Comment by stbui** [comment]
是window系统吧
