### ISSUE TITLE
请问如何在mat-icon中使用自定义的图标呢？

### ISSUE THREAD

**Issue by cjwddz** [stbui/angular-material-app#9]
你好，感谢开源这样优秀的项目，收益良多。此外，请问我应该如何在mat-icon中使用自定义的图标呢？或者在那里可以预览全部可选的图标呢？

**Comment by stbui** [comment]
你好，图标例子已经添加到项目中了，自定义图标官网已经给出例子了参考下。


参考链接：

官网文档
https://material.angular.io/components/icon/overview

图标字体列表
https://material.io/icons/

**Comment by cjwddz** [comment]
好的，非常感谢！
